Upgrade + surf reload patch

diff --git a/usr/bin/bashbug b/usr/bin/bashbug
--- a/usr/bin/bashbug
+++ b/usr/bin/bashbug
@@ -29,9 +29,9 @@
 MACHINE="armv7l"
 OS="linux-gnueabihf"
 CC="gcc"
-CFLAGS=" -DPROGRAM='bash' -DCONF_HOSTTYPE='armv7l' -DCONF_OSTYPE='linux-gnueabihf' -DCONF_MACHTYPE='armv7l-unknown-linux-gnueabihf' -DCONF_VENDOR='unknown' -DLOCALEDIR='/usr/share/locale' -DPACKAGE='bash' -DSHELL -DHAVE_CONFIG_H   -I.  -I. -I./include -I./lib  -D_FORTIFY_SOURCE=2 -march=armv7-a -mfloat-abi=hard -mfpu=vfpv3-d16 -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -DDEFAULT_PATH_VALUE='/usr/local/sbin:/usr/local/bin:/usr/bin' -DSTANDARD_UTILS_PATH='/usr/bin' -DSYS_BASHRC='/etc/bash.bashrc' -DSYS_BASH_LOGOUT='/etc/bash.bash_logout'"
-RELEASE="4.3"
-PATCHLEVEL="33"
+CFLAGS=" -DPROGRAM='bash' -DCONF_HOSTTYPE='armv7l' -DCONF_OSTYPE='linux-gnueabihf' -DCONF_MACHTYPE='armv7l-unknown-linux-gnueabihf' -DCONF_VENDOR='unknown' -DLOCALEDIR='/usr/share/locale' -DPACKAGE='bash' -DSHELL -DHAVE_CONFIG_H   -I.  -I. -I./include -I./lib  -D_FORTIFY_SOURCE=2 -march=armv7-a -mfloat-abi=hard -mfpu=vfpv3-d16 -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -DDEFAULT_PATH_VALUE='/usr/local/sbin:/usr/local/bin:/usr/bin' -DSTANDARD_UTILS_PATH='/usr/bin' -DSYS_BASHRC='/etc/bash.bashrc' -DSYS_BASH_LOGOUT='/etc/bash.bash_logout' -DNON_INTERACTIVE_LOGIN_SHELLS -Wno-parentheses -Wno-format-security"
+RELEASE="4.4"
+PATCHLEVEL="12"
 RELSTATUS="release"
 MACHTYPE="armv7l-unknown-linux-gnueabihf"
 
@@ -62,7 +62,7 @@ while [ $# -gt 0 ]; do
 	--version)	shift ; do_version=y ;;
 	--)		shift ; break ;;
 	-*)		echo "bashbug: ${1}: invalid option" >&2
-			echo "$USAGE" >& 2
+			echo "$USAGE" >&2
 			exit 2 ;;
 	*)		break ;;
 	esac
@@ -265,7 +265,8 @@ esac
 
 ${RMAIL} $SMARGS < "$TEMPFILE1" || {
 	cat "$TEMPFILE1" >> $HOME/dead.bashbug
-	echo "$0: mail failed: report saved in $HOME/dead.bashbug" >&2
+	echo "$0: mail to ${BUGADDR} failed: report saved in $HOME/dead.bashbug" >&2
+	echo "$0: please send it manually to ${BUGADDR}" >&2
 }
 
 exit 0
diff --git a/usr/bin/blkdeactivate b/usr/bin/blkdeactivate
--- a/usr/bin/blkdeactivate
+++ b/usr/bin/blkdeactivate
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# Copyright (C) 2012-2013 Red Hat, Inc. All rights reserved.
+# Copyright (C) 2012-2015 Red Hat, Inc. All rights reserved.
 #
 # This file is part of LVM2.
 #
@@ -10,7 +10,7 @@
 #
 # You should have received a copy of the GNU General Public License
 # along with this program; if not, write to the Free Software Foundation,
-# Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
+# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 #
 # Author: Peter Rajnoha <prajnoha at redhat.com>
 #
@@ -18,8 +18,10 @@
 #
 # Requires:
 #   bash >= 4.0 (associative array support)
-#   lsblk >= 2.22 (lsblk -s support)
-#   umount
+#   util-linux {
+#       lsblk >= 2.22 (lsblk -s support)
+#       umount
+#   }
 #   dmsetup >= 1.02.68 (--retry option support)
 #   lvm >= 2.2.89 (activation/retry_deactivation config support)
 #
@@ -32,9 +34,12 @@ TOOL=blkdeactivate
 DEV_DIR='/dev'
 SYS_BLK_DIR='/sys/block'
 
+MOUNTPOINT="/bin/mountpoint"
 UMOUNT="/bin/umount"
 DMSETUP="/usr/bin/dmsetup"
 LVM="/usr/bin/lvm"
+MDADM="/usr/bin/mdadm"
+MPATHD="/sbin/multipathd"
 
 if $UMOUNT --help | grep -- "--all-targets" >$DEV_DIR/null; then
 	UMOUNT_OPTS="--all-targets "
@@ -45,6 +50,8 @@ else
 fi
 DMSETUP_OPTS=""
 LVM_OPTS=""
+MDADM_OPTS=""
+MPATHD_OPTS=""
 
 LSBLK="/bin/lsblk -r --noheadings -o TYPE,KNAME,NAME,MOUNTPOINT"
 LSBLK_VARS="local devtype local kname local name local mnt"
@@ -63,6 +70,9 @@ DO_UMOUNT=0
 LVM_DO_WHOLE_VG=0
 # Do not retry LV deactivation by default.
 LVM_CONFIG="activation{retry_deactivation=0}"
+
+# Do not disable queueing if set on multipath devices.
+MPATHD_DO_DISABLEQUEUEING=0
 
 #
 # List of device names and/or VGs to be skipped.
@@ -103,20 +113,23 @@ usage() {
 	echo "      If devices are specified, deactivate only supplied devices and their holders."
 	echo
 	echo "  Options:"
-	echo "    -e | --errors                Show errors reported from tools"
-	echo "    -h | --help                  Show this help message"
-	echo "    -d | --dmoption  DM_OPTIONS  Comma separated DM specific options"
-	echo "    -l | --lvmoption LVM_OPTIONS Comma separated LVM specific options"
-	echo "    -u | --umount                Unmount the device if mounted"
-	echo "    -v | --verbose               Verbose mode (also implies -e)"
+	echo "    -e | --errors                    Show errors reported from tools"
+	echo "    -h | --help                      Show this help message"
+	echo "    -d | --dmoption    DM_OPTIONS    Comma separated DM specific options"
+	echo "    -l | --lvmoption   LVM_OPTIONS   Comma separated LVM specific options"
+	echo "    -m | --mpathoption MPATH_OPTIONS Comma separated DM-multipath specific options"
+	echo "    -u | --umount                    Unmount the device if mounted"
+	echo "    -v | --verbose                   Verbose mode (also implies -e)"
 	echo
 	echo "  Device specific options:"
 	echo "    DM_OPTIONS:"
-	echo "      retry    retry removal several times in case of failure"
-	echo "      force    force device removal"
+	echo "      retry           retry removal several times in case of failure"
+	echo "      force           force device removal"
 	echo "    LVM_OPTIONS:"
-	echo "      retry    retry removal several times in case of failure"
-	echo "      wholevg  deactivate the whole VG when processing an LV"
+	echo "      retry           retry removal several times in case of failure"
+	echo "      wholevg         deactivate the whole VG when processing an LV"
+	echo "    MPATH_OPTIONS:"
+	echo "      disablequeueing disable queueing on all DM-multipath devices first"
 
 	exit
 }
@@ -143,11 +156,13 @@ device_umount_one() {
 
 	if test -z "${SKIP_UMOUNT_LIST["$mnt"]}" -a "$DO_UMOUNT" -eq "1"; then
 		echo -n "  [UMOUNT]: unmounting $name ($kname) mounted on $mnt... "
-		if eval $UMOUNT $UMOUNT_OPTS "$(printf $mnt)" $OUT $ERR; then
+		if eval $UMOUNT $UMOUNT_OPTS "$(printf "%s" "$mnt")" $OUT $ERR; then
 			echo "done"
-		else
+		elif $MOUNTPOINT -q "$mnt"; then
 			echo "skipping"
 			add_device_to_skip_list
+		else
+			echo "already unmounted"
 		fi
 	else
 		echo "  [SKIP]: unmount of $name ($kname) mounted on $mnt"
@@ -156,7 +171,8 @@ device_umount_one() {
 }
 
 device_umount() {
-	test "$devtype" != "lvm" && test "${kname:0:3}" != "dm-" && return 0
+	test "$devtype" != "lvm" && test "${kname:0:3}" != "dm-" \
+          && test "${kname:0:2}" != "md" && return 0
 
 	# FINDMNT is defined only if umount --all-targets is not available.
 	# In that case, read the list of multiple mount points of one device
@@ -189,7 +205,7 @@ deactivate_holders () {
 }
 
 deactivate_dm () {
-	local name=$(printf $name)
+	local name=$(printf "%s" "$name")
 	test -b "$DEV_DIR/mapper/$name" || return 0
 	test -z ${SKIP_DEVICE_LIST["$kname"]} || return 1
 
@@ -212,6 +228,11 @@ deactivate_lvm () {
 	test -z ${SKIP_VG_LIST["$DM_VG_NAME"]} || return 1
 
 	if test $LVM_DO_WHOLE_VG -eq 0; then
+		# Skip LVM device deactivation if LVM tools missing.
+		test $LVM_AVAILABLE -eq 0 && {
+			add_device_to_skip_list
+			return 1
+		}
 		# Deactivating only the LV specified
 		deactivate_holders "$DEV_DIR/$DM_VG_NAME/$DM_LV_NAME" || {
 			add_device_to_skip_list
@@ -227,6 +248,11 @@ deactivate_lvm () {
 		fi
 
 	else
+		# Skip LVM VG deactivation if LVM tools missing.
+		test $LVM_AVAILABLE -eq 0 && {
+			add_vg_to_skip_list
+			return 1
+		}
 		# Deactivating the whole VG the LV is part of
 		lv_list=$(eval $LVM vgs --config "$LVM_CONFIG" --noheadings --rows -o lv_name $DM_VG_NAME $ERR)
 		for lv in $lv_list; do
@@ -244,6 +270,28 @@ deactivate_lvm () {
 			echo "skipping"
 			add_vg_to_skip_list
 		fi
+	fi
+}
+
+deactivate_md () {
+	local name=$(printf "%s" "$name")
+	test -b "$DEV_DIR/$name" || return 0
+	test -z ${SKIP_DEVICE_LIST["$kname"]} || return 1
+
+	# Skip MD device deactivation if MD tools missing.
+	test $MDADM_AVAILABLE -eq 0 && {
+		add_device_to_skip_list
+		return 1
+	}
+
+	deactivate_holders "$DEV_DIR/$name" || return 1
+
+	echo -n "  [MD]: deactivating $devtype device $kname... "
+	if eval $MDADM $MDADM_OPTS -S "$name" $OUT $ERR; then
+		echo "done"
+	else
+		echo "skipping"
+		add_device_to_skip_list
 	fi
 }
 
@@ -265,6 +313,8 @@ deactivate () {
 		deactivate_lvm
 	elif test "${kname:0:3}" = "dm-"; then
 		deactivate_dm
+	elif test "${kname:0:2}" = "md"; then
+		deactivate_md
 	fi
 }
 
@@ -273,6 +323,11 @@ deactivate_all() {
 	skip=0
 
 	echo "Deactivating block devices:"
+
+	test $MPATHD_RUNNING -eq 1 && {
+		echo -n "  [DM]: disabling queueing on all multipath devices... "
+		eval $MPATHD $MPATHD_OPTS disablequeueing maps $ERR | grep '^ok$' >$DEV_DIR/null && echo "done" || echo "failed"
+	}
 
 	if test $# -eq 0; then
 		#######################
@@ -368,6 +423,20 @@ get_lvmopts() {
 	IFS=$ORIG_IFS
 }
 
+get_mpathopts() {
+	ORIG_IFS=$IFS; IFS=','
+
+	for opt in $1; do
+		case "$opt" in
+			"") ;;
+			"disablequeueing") MPATHD_DO_DISABLEQUEUEING=1 ;;
+			*) echo "$opt: unknown DM-multipath option"
+		esac
+	done
+
+	IFS=$ORIG_IFS
+}
+
 set_env() {
 	if test "$ERRORS" -eq "1"; then
 		unset ERR
@@ -380,9 +449,32 @@ set_env() {
 		UMOUNT_OPTS+="-v"
 		DMSETUP_OPTS+="-vvvv"
 		LVM_OPTS+="-vvvv"
+		MDADM_OPTS+="-vv"
+		MPATHD_OPTS+="-v 3"
 	else
 		OUT="1>$DEV_DIR/null"
 	fi
+
+	if test -f $LVM; then
+		LVM_AVAILABLE=1
+	else
+		LVM_AVAILABLE=0
+	fi
+
+	if test -f $MDADM; then
+		MDADM_AVAILABLE=1
+	else
+		MDADM_AVAILABLE=0
+	fi
+
+	MPATHD_RUNNING=0
+	test $MPATHD_DO_DISABLEQUEUEING -eq 1 && {
+		if test -f $MPATHD; then
+			if eval $MPATHD show daemon $ERR | grep "running" >$DEV_DIR/null; then
+				MPATHD_RUNNING=1
+			fi
+		fi
+	}
 }
 
 while test $# -ne 0; do
@@ -392,6 +484,7 @@ while test $# -ne 0; do
 		"-h"|"--help") usage ;;
 		"-d"|"--dmoption ") get_dmopts "$2" ; shift ;;
 		"-l"|"--lvmoption ") get_lvmopts "$2" ; shift ;;
+		"-m"|"--mpathoption ") get_mpathopts "$2" ; shift ;;
 		"-u"|"--umount") DO_UMOUNT=1 ;;
 		"-v"|"--verbose") VERBOSE=1 ; ERRORS=1 ;;
 		"-vv") VERBOSE=1 ; ERRORS=1 ; set -x ;;
diff --git a/usr/bin/fsadm b/usr/bin/fsadm
--- a/usr/bin/fsadm
+++ b/usr/bin/fsadm
@@ -10,7 +10,7 @@
 #
 # You should have received a copy of the GNU General Public License
 # along with this program; if not, write to the Free Software Foundation,
-# Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
+# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 #
 # Author: Zdenek Kabelac <zkabelac at redhat.com>
 #
@@ -76,6 +76,7 @@ MOUNTPOINT=
 MOUNTED=
 REMOUNT=
 PROCMOUNTS="/proc/mounts"
+PROCSELFMOUNTINFO="/proc/self/mountinfo"
 NULL="$DM_DEV_DIR/null"
 
 IFS_OLD=$IFS
@@ -86,10 +87,10 @@ NL='
 tool_usage() {
 	echo "${TOOL}: Utility to resize or check the filesystem on a device"
 	echo
-	echo "  ${TOOL} [options] check device"
+	echo "  ${TOOL} [options] check <device>"
 	echo "    - Check the filesystem on device using fsck"
 	echo
-	echo "  ${TOOL} [options] resize device [new_size[BKMGTPE]]"
+	echo "  ${TOOL} [options] resize <device> [<new_size>[BKMGTPE]]"
 	echo "    - Change the size of the filesystem on device to new_size"
 	echo
 	echo "  Options:"
@@ -188,6 +189,14 @@ detect_fs() {
           # hardcoded /dev  since udev does not create these entries elsewhere
 	  /dev/dm-[0-9]*)
 		read </sys/block/${RVOLUME#/dev/}/dm/name SYSVOLUME 2>&1 && VOLUME="$DM_DEV_DIR/mapper/$SYSVOLUME"
+		read </sys/block/${RVOLUME#/dev/}/dev MAJORMINOR 2>&1 || error "Cannot get major:minor for \"$VOLUME\""
+		;;
+	  *)
+		STAT=$(stat --format "MAJOR=%t MINOR=%T" ${RVOLUME}) || error "Cannot get major:minor for \"$VOLUME\""
+		eval $STAT
+		MAJOR=$((0x${MAJOR}))
+		MINOR=$((0x${MINOR}))
+		MAJORMINOR=${MAJOR}:${MINOR}
 		;;
 	esac
 	# use null device as cache file to be sure about the result
@@ -198,11 +207,18 @@ detect_fs() {
 	verbose "\"$FSTYPE\" filesystem found on \"$VOLUME\""
 }
 
-# check if the given device is already mounted and where
-# FIXME: resolve swap usage and device stacking
-detect_mounted()  {
-	test -e "$PROCMOUNTS" || error "Cannot detect mounted device \"$VOLUME\""
+detect_mounted_with_proc_self_mountinfo()  {
+	MOUNTED=$("$GREP" "^[0-9]* [0-9]* $MAJORMINOR " "$PROCSELFMOUNTINFO")
 
+	# extract 5th field which is mount point
+	# echo -e translates \040 to spaces
+	MOUNTED=$(echo ${MOUNTED} | cut -d " " -f 5)
+	MOUNTED=$(echo -n -e ${MOUNTED})
+
+	test -n "$MOUNTED"
+}
+
+detect_mounted_with_proc_mounts()  {
 	MOUNTED=$("$GREP" "^$VOLUME[ \t]" "$PROCMOUNTS")
 
 	# for empty string try again with real volume name
@@ -222,6 +238,18 @@ detect_mounted()  {
 	fi
 
 	test -n "$MOUNTED"
+}
+
+# check if the given device is already mounted and where
+# FIXME: resolve swap usage and device stacking
+detect_mounted()  {
+	if test -e "$PROCSELFMOUNTINFO"; then
+		detect_mounted_with_proc_self_mountinfo
+	elif test -e "$PROCMOUNTS"; then
+		detect_mounted_with_proc_mounts
+	else
+		error "Cannot detect mounted device \"$VOLUME\""
+	fi
 }
 
 # get the full size of device in bytes
diff --git a/usr/bin/lvmdump b/usr/bin/lvmdump
--- a/usr/bin/lvmdump
+++ b/usr/bin/lvmdump
@@ -1,7 +1,7 @@
 #!/bin/bash
 # We use some bash-isms (getopts?)
 
-# Copyright (C) 2007-2010 Red Hat, Inc. All rights reserved.
+# Copyright (C) 2007-2015 Red Hat, Inc. All rights reserved.
 #
 # This file is part of LVM2.
 #
@@ -11,7 +11,7 @@
 #
 # You should have received a copy of the GNU General Public License
 # along with this program; if not, write to the Free Software Foundation,
-# Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
+# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 
 # lvm_dump: This script is used to collect pertinent information for
 #           the debugging of lvm issues.
@@ -28,6 +28,7 @@ PS=ps # need alx
 SED=sed
 DD=dd
 CUT=cut
+GREP=grep
 DATE=date
 BASENAME=basename
 UDEVADM=udevadm
@@ -36,11 +37,18 @@ TR=tr
 SOCAT=socat # either socat or nc is needed for dumping lvmetad state
 NC=nc
 
+if test "yes" = yes; then
+    DDFLAGS='iflag=direct oflag=direct'
+else
+    DDFLAGS=
+fi
+
 # user may override lvm and dmsetup location by setting LVM_BINARY
 # and DMSETUP_BINARY respectively
 LVM=${LVM_BINARY-lvm}
 DMSETUP=${DMSETUP_BINARY-dmsetup}
 LVMETAD_SOCKET=${LVM_LVMETAD_SOCKET-/var/run/lvm/lvmetad.socket}
+LVMPOLLD_SOCKET=${LVM_LVMPOLLD_SOCKET-/var/run/lvm/lvmpolld.socket}
 
 die() {
     code=$1; shift
@@ -59,6 +67,7 @@ function usage {
 	echo "    -c if running clvmd, gather cluster data as well"
 	echo "    -d <directory> dump into a directory instead of tarball"
 	echo "    -l gather lvmetad state if running"
+	echo "    -p gather lvmpolld state if running"
 	echo "    -m gather LVM metadata from the PVs"
 	echo "    -s gather system info and context"
 	echo "    -u gather udev info and context"
@@ -72,13 +81,14 @@ clustered=0
 metadata=0
 sysreport=0
 udev=0
-while getopts :acd:hlmus opt; do
+while getopts :acd:hlpmus opt; do
 	case $opt in 
 		a)	advanced=1 ;;
 		c)	clustered=1 ;;
 		d)	userdir=$OPTARG ;;
 		h)	usage ;;
 		l)	lvmetad=1 ;;
+		p)	lvmpolld=1 ;;
 		m)	metadata=1 ;;
 		s)      sysreport=1 ;;
 		u)	udev=1 ;;
@@ -96,8 +106,13 @@ else
 	dir="$HOME/$dirbase"
 fi
 
-test -e $dir && die 3 "Fatal: $dir already exists"
-$MKDIR -p $dir || die 4 "Fatal: could not create $dir"
+if test -d $dir ; then
+	(shopt -s nullglob dotglob; test -r $dir -a -w $dir -a -x $dir && cd $dir && files=(*) && ((! ${#files[@]}))) || \
+		die 5 "Fatal: directory $dir already exists and is not empty or inaccessible"
+else
+	test -e $dir && die 3 "Fatal: $dir already exists"
+	$MKDIR -p $dir || die 4 "Fatal: could not create $dir"
+fi
 
 log="$dir/lvmdump.log"
 
@@ -134,10 +149,10 @@ if (( $advanced )); then
 	log "\"$LVM\" pvscan -v >> \"$dir/pvscan\" 2>> \"$log\""
 
 	myecho "  lvs..."
-	log "\"$LVM\" lvs -a -o +devices >> \"$dir/lvs\" 2>> \"$log\""
+	log "\"$LVM\" lvs -a -H -o +devices,kernel_major,kernel_minor >> \"$dir/lvs\" 2>> \"$log\""
 
 	myecho "  pvs..."
-	log "\"$LVM\" pvs -a -v >> \"$dir/pvs\" 2>> \"$log\""
+	log "\"$LVM\" pvs -a -o +major,minor -v >> \"$dir/pvs\" 2>> \"$log\""
 
 	myecho "  vgs..."
 	log "\"$LVM\" vgs -v >> \"$dir/vgs\" 2>> \"$log\""
@@ -232,7 +247,7 @@ if (( $metadata )); then
 		pe_start="$(echo $line | $CUT -d, -f2)"
 		name="$($BASENAME "$pv")"
 		myecho "  $pv"
-		log "$DD if=$pv \"of=$dir/metadata/$name\" bs=512 count=$pe_start 2>> \"$log\""
+		log "$DD if=$pv \"of=$dir/metadata/$name\" $DDFLAGS bs=512 count=$pe_start 2>> \"$log\""
 	done
 fi
 
@@ -244,23 +259,42 @@ if (( $sysreport )); then
 
 	SYSTEMCTL=$(which systemctl 2>> $log)
 	JOURNALCTL=$(which journalctl 2>> $log)
+	LSBLK=$(which lsblk 2>> $log)
+
+	log "$MKDIR -p \"$sysreport_dir\""
+
+	if test -z "LSBLK"; then
+		myecho "WARNING: lsblk not found"
+	else
+		if $LSBLK --help | $GREP -- --output-all >/dev/null; then
+			log "$LSBLK -O >> \"$sysreport_dir/lsblk_O\""
+		else
+			log "$LSBLK >> \"$sysreport_dir/lsblk\""
+		fi
+		if $LSBLK --help | $GREP -- --inverse >/dev/null; then
+			log "$LSBLK -s >> \"$sysreport_dir/lsblk_s\""
+		fi
+	fi
 
 	if test -z "$SYSTEMCTL"; then
 		myecho "WARNING: systemctl not found"
 	elif test -z "$JOURNALCTL"; then
 		myecho "WARNING: journalctl not found"
 	else
-		log "$MKDIR -p \"$sysreport_dir\""
 		log "$JOURNALCTL -b --no-pager -o short-precise > \"$sysreport_dir/journal_content\" 2>> \"$log\""
 		log "$SYSTEMCTL status -l --no-pager -n $log_lines -o short-precise dm-event.socket dm-event.service \
 						   lvm2-monitor.service \
 						   lvm2-lvmetad.socket lvm2-lvmetad.service \
+						   lvm2-lvmpolld.socket lvm2-lvmpolld.service \
 						   lvm2-cluster-activation.service \
 						   lvm2-clvmd.service \
 						   lvm2-cmirrord.service \
+						   lvm2-activation-early.service \
+						   lvm2-activation.service \
+						   lvm2-activation-net.service \
 						   > \"$sysreport_dir/systemd_lvm2_services_status\" 2>> \"$log\""
 		log "$SYSTEMCTL list-units -l -a --no-legend --no-pager > \"$sysreport_dir/systemd_unit_list\" 2>> \"$log\""
-		for unit in $(cat $sysreport_dir/systemd_unit_list | grep lvm2-pvscan | cut -d " " -f 1); do
+		for unit in $(cat $sysreport_dir/systemd_unit_list | $GREP lvm2-pvscan | cut -d " " -f 1); do
 			log "$SYSTEMCTL status -l --no-pager -n $log_lines -o short-precise $unit >> \"$sysreport_dir/systemd_lvm2_pvscan_service_status\""
 		done
 	fi
@@ -294,6 +328,22 @@ if (( $lvmetad )); then
 	    return 1
 	fi
     } > "$dir/lvmetad.txt"
+fi
+
+if (( $lvmpolld )); then
+    (echo 'request="dump"'; echo '##') | {
+	if type -p $SOCAT >& /dev/null; then
+	    echo "$SOCAT unix-connect:$LVMPOLLD_SOCKET -" >> "$log"
+	    $SOCAT "unix-connect:$LVMPOLLD_SOCKET" - 2>> "$log"
+	elif echo | $NC -U "$LVMPOLLD_SOCKET"; then
+	    echo "$NC -U $LVMPOLLD_SOCKET" >> "$log"
+	    $NC -U "$LVMPOLLD_SOCKET" 2>> "$log"
+	else
+	    myecho "WARNING: Neither socat nor nc -U seems to be available." 1>&2
+	    echo "# DUMP FAILED"
+	    return 1
+	fi
+    } > "$dir/lvmpolld.txt"
 fi
 
 if test -z "$userdir"; then
diff --git a/usr/bin/mk_cmds b/usr/bin/mk_cmds
--- a/usr/bin/mk_cmds
+++ b/usr/bin/mk_cmds
@@ -3,8 +3,7 @@
 #
 
 datarootdir=/usr/share
-DIR="${DIR-/usr/share/ss}"
-SS_DIR="/usr/share/ss"
+DIR=/usr/share/ss
 AWK=gawk
 SED=/usr/bin/sed
 
@@ -30,12 +29,8 @@ if test -n "$_SS_DIR_OVERRIDE" ; then
 fi
 
 if test ! -f $DIR/ct_c.sed || test ! -f $DIR/ct_c.awk ; then
-    DIR="$SS_DIR"
-#    echo "Falling back to $DIR..."
-    if test ! -f "$DIR/ct_c.sed" || test ! -f "$DIR/ct_c.awk" ; then
-	echo "mk_cmds: Couldn't find mk_cmds's template files."
-	exit 1
-    fi
+    echo "mk_cmds: Couldn't find mk_cmds's template files."
+    exit 1
 fi
 
 FILE="$1"
@@ -57,6 +52,6 @@ if grep "^#__ERROR_IN_FILE" "${TMP}" > /dev/null; then
 else
 	rm -f "${BASE}.c"
 	mv -f "${TMP}" "${BASE}.c"
-	chmod -w "${BASE}.c"
+	chmod a-w "${BASE}.c"
 	exit 0
 fi
diff --git a/usr/lib/git-core/git-rebase b/usr/lib/git-core/git-rebase
--- a/usr/lib/git-core/git-rebase
+++ b/usr/lib/git-core/git-rebase
@@ -14,7 +14,7 @@ git-rebase --continue | --abort | --skip | --edit-todo
  Available options are
 v,verbose!         display a diffstat of what changed upstream
 q,quiet!           be quiet. implies --no-stat
-autostash!         automatically stash/stash pop before and after
+autostash          automatically stash/stash pop before and after
 fork-point         use 'merge-base --fork-point' to refine upstream
 onto=!             rebase onto given branch instead of upstream
 p,preserve-merges! try to recreate merges instead of ignoring them
@@ -43,9 +43,9 @@ continue!          continue
 abort!             abort and check out the original branch
 skip!              skip current patch and continue
 edit-todo!         edit the todo list during an interactive rebase
+quit!              abort but keep HEAD where it is
 "
 . git-sh-setup
-. git-sh-i18n
 set_reflog_action rebase
 require_work_tree_exists
 cd_to_toplevel
@@ -87,7 +87,10 @@ preserve_merges=
 autosquash=
 keep_empty=
 test "$(git config --bool rebase.autosquash)" = "true" && autosquash=t
-gpg_sign_opt=
+case "$(git config --bool commit.gpgsign)" in
+true)	gpg_sign_opt=-S ;;
+*)	gpg_sign_opt= ;;
+esac
 
 read_basic_state () {
 	test -f "$state_dir/head-name" &&
@@ -151,7 +154,7 @@ move_to_original_branch () {
 		git symbolic-ref \
 			-m "rebase finished: returning to $head_name" \
 			HEAD $head_name ||
-		die "$(gettext "Could not move back to $head_name")"
+		die "$(eval_gettext "Could not move back to \$head_name")"
 		;;
 	esac
 }
@@ -176,7 +179,7 @@ You can run "git stash pop" or "git stash drop" at any time.
 
 finish_rebase () {
 	apply_autostash &&
-	git gc --auto &&
+	{ git gc --auto || true; } &&
 	rm -rf "$state_dir"
 }
 
@@ -202,9 +205,9 @@ run_specific_rebase () {
 
 run_pre_rebase_hook () {
 	if test -z "$ok_to_skip_pre_rebase" &&
-	   test -x "$GIT_DIR/hooks/pre-rebase"
+	   test -x "$(git rev-parse --git-path hooks/pre-rebase)"
 	then
-		"$GIT_DIR/hooks/pre-rebase" ${1+"$@"} ||
+		"$(git rev-parse --git-path hooks/pre-rebase)" ${1+"$@"} ||
 		die "$(gettext "The pre-rebase hook refused to rebase.")"
 	fi
 }
@@ -239,7 +242,7 @@ do
 	--verify)
 		ok_to_skip_pre_rebase=
 		;;
-	--continue|--skip|--abort|--edit-todo)
+	--continue|--skip|--abort|--quit|--edit-todo)
 		test $total_argc -eq 2 || usage
 		action=${1##--}
 		;;
@@ -248,6 +251,7 @@ do
 		;;
 	--exec=*)
 		cmd="${cmd}exec ${1#--exec=}${LF}"
+		test -z "$interactive_rebase" && interactive_rebase=implied
 		;;
 	--interactive)
 		interactive_rebase=explicit
@@ -291,6 +295,9 @@ do
 		;;
 	--autostash)
 		autostash=true
+		;;
+	--no-autostash)
+		autostash=false
 		;;
 	--verbose)
 		verbose=t
@@ -345,12 +352,6 @@ do
 done
 test $# -gt 2 && usage
 
-if test -n "$cmd" &&
-   test "$interactive_rebase" != explicit
-then
-	die "$(gettext "The --exec option must be used with the --interactive option")"
-fi
-
 if test -n "$action"
 then
 	test -z "$in_progress" && die "$(gettext "No rebase in progress?")"
@@ -398,6 +399,9 @@ abort)
 	output git reset --hard $orig_head
 	finish_rebase
 	exit
+	;;
+quit)
+	exec rm -rf "$state_dir"
 	;;
 edit-todo)
 	run_specific_rebase
@@ -448,7 +452,7 @@ then
 		then
 			. git-parse-remote
 			error_on_missing_default_upstream "rebase" "rebase" \
-				"against" "git rebase <branch>"
+				"against" "git rebase $(gettext '<branch>')"
 		fi
 
 		test "$fork_point" = auto && fork_point=t
@@ -582,7 +586,7 @@ then
 		# Lazily switch to the target branch if needed...
 		test -z "$switch_to" ||
 		GIT_REFLOG_ACTION="$GIT_REFLOG_ACTION: checkout $switch_to" \
-			git checkout "$switch_to" --
+			git checkout -q "$switch_to" --
 		say "$(eval_gettext "Current branch \$branch_name is up to date.")"
 		finish_rebase
 		exit 0
diff --git a/usr/lib/git-core/git-stash b/usr/lib/git-core/git-stash
--- a/usr/lib/git-core/git-stash
+++ b/usr/lib/git-core/git-stash
@@ -15,12 +15,11 @@ SUBDIRECTORY_OK=Yes
 OPTIONS_SPEC=
 START_DIR=$(pwd)
 . git-sh-setup
-. git-sh-i18n
 require_work_tree
 cd_to_toplevel
 
 TMP="$GIT_DIR/.git-stash.$$"
-TMPindex=${GIT_INDEX_FILE-"$GIT_DIR/index"}.stash.$$
+TMPindex=${GIT_INDEX_FILE-"$(git rev-parse --git-path index)"}.stash.$$
 trap 'rm -f "$TMP-"* "$TMPindex"' 0
 
 ref_stash=refs/stash
@@ -101,7 +100,7 @@ create_stash () {
 				u_tree=$(git write-tree) &&
 				printf 'untracked files on %s\n' "$msg" | git commit-tree $u_tree  &&
 				rm -f "$TMPindex"
-		) ) || die "Cannot save the untracked files"
+		) ) || die "$(gettext "Cannot save the untracked files")"
 
 		untracked_commit_option="-p $u_commit";
 	else
@@ -116,7 +115,7 @@ create_stash () {
 			git read-tree --index-output="$TMPindex" -m $i_tree &&
 			GIT_INDEX_FILE="$TMPindex" &&
 			export GIT_INDEX_FILE &&
-			git diff --name-only -z HEAD -- >"$TMP-stagenames" &&
+			git diff-index --name-only -z HEAD -- >"$TMP-stagenames" &&
 			git update-index -z --add --remove --stdin <"$TMP-stagenames" &&
 			git write-tree &&
 			rm -f "$TMPindex"
@@ -183,11 +182,9 @@ store_stash () {
 		stash_msg="Created via \"git stash store\"."
 	fi
 
-	# Make sure the reflog for stash is kept.
-	: >>"$GIT_DIR/logs/$ref_stash"
-	git update-ref -m "$stash_msg" $ref_stash $w_commit
+	git update-ref --create-reflog -m "$stash_msg" $ref_stash $w_commit
 	ret=$?
-	test $ret != 0 && test -z $quiet &&
+	test $ret != 0 && test -z "$quiet" &&
 	die "$(eval_gettext "Cannot update \$ref_stash with \$w_commit")"
 	return $ret
 }
@@ -219,6 +216,9 @@ save_stash () {
 		-a|--all)
 			untracked=all
 			;;
+		--help)
+			show_help
+			;;
 		--)
 			shift
 			break
@@ -248,7 +248,7 @@ save_stash () {
 
 	if test -n "$patch_mode" && test -n "$untracked"
 	then
-	    die "Can't use --patch and --include-untracked or --all at the same time"
+		die "$(gettext "Can't use --patch and --include-untracked or --all at the same time")"
 	fi
 
 	stash_msg="$*"
@@ -259,13 +259,13 @@ save_stash () {
 		say "$(gettext "No local changes to save")"
 		exit 0
 	fi
-	test -f "$GIT_DIR/logs/$ref_stash" ||
+	git reflog exists $ref_stash ||
 		clear_stash || die "$(gettext "Cannot initialize stash")"
 
 	create_stash "$stash_msg" $untracked
 	store_stash -m "$stash_msg" -q $w_commit ||
 	die "$(gettext "Cannot save the current status")"
-	say Saved working directory and index state "$stash_msg"
+	say "$(eval_gettext "Saved working directory and index state \$stash_msg")"
 
 	if test -z "$patch_mode"
 	then
@@ -276,7 +276,7 @@ save_stash () {
 			git clean --force --quiet -d $CLEAN_X_OPTION
 		fi
 
-		if test "$keep_index" = "t" && test -n $i_tree
+		if test "$keep_index" = "t" && test -n "$i_tree"
 		then
 			git read-tree --reset -u $i_tree
 		fi
@@ -301,9 +301,33 @@ list_stash () {
 }
 
 show_stash () {
+	ALLOW_UNKNOWN_FLAGS=t
 	assert_stash_like "$@"
 
-	git diff ${FLAGS:---stat} $b_commit $w_commit
+	if test -z "$FLAGS"
+	then
+		if test "$(git config --bool stash.showStat || echo true)" = "true"
+		then
+			FLAGS=--stat
+		fi
+
+		if test "$(git config --bool stash.showPatch || echo false)" = "true"
+		then
+			FLAGS=${FLAGS}${FLAGS:+ }-p
+		fi
+
+		if test -z "$FLAGS"
+		then
+			return 0
+		fi
+	fi
+
+	git diff ${FLAGS} $b_commit $w_commit
+}
+
+show_help () {
+	exec git help stash
+	exit 1
 }
 
 #
@@ -332,13 +356,14 @@ show_stash () {
 #
 #   GIT_QUIET is set to t if -q is specified
 #   INDEX_OPTION is set to --index if --index is specified.
-#   FLAGS is set to the remaining flags
+#   FLAGS is set to the remaining flags (if allowed)
 #
 # dies if:
 #   * too many revisions specified
 #   * no revision is specified and there is no stash stack
 #   * a revision is specified which cannot be resolve to a SHA1
 #   * a non-existent stash reference is specified
+#   * unknown flags were set and ALLOW_UNKNOWN_FLAGS is not "t"
 #
 
 parse_flags_and_rev()
@@ -359,9 +384,8 @@ parse_flags_and_rev()
 	i_tree=
 	u_tree=
 
-	REV=$(git rev-parse --no-flags --symbolic --sq "$@") || exit 1
-
 	FLAGS=
+	REV=
 	for opt
 	do
 		case "$opt" in
@@ -371,8 +395,16 @@ parse_flags_and_rev()
 			--index)
 				INDEX_OPTION=--index
 			;;
+			--help)
+				show_help
+			;;
 			-*)
+				test "$ALLOW_UNKNOWN_FLAGS" = t ||
+					die "$(eval_gettext "unknown option: \$opt")"
 				FLAGS="${FLAGS}${FLAGS:+ }$opt"
+			;;
+			*)
+				REV="${REV}${REV:+ }'$opt'"
 			;;
 		esac
 	done
@@ -389,6 +421,15 @@ parse_flags_and_rev()
 		;;
 		*)
 			die "$(eval_gettext "Too many revisions specified: \$REV")"
+		;;
+	esac
+
+	case "$1" in
+		*[!0-9]*)
+			:
+		;;
+		*)
+			set -- "${ref_stash}@{$1}"
 		;;
 	esac
 
@@ -464,7 +505,7 @@ apply_stash () {
 		GIT_INDEX_FILE="$TMPindex" git-read-tree "$u_tree" &&
 		GIT_INDEX_FILE="$TMPindex" git checkout-index --all &&
 		rm -f "$TMPindex" ||
-		die 'Could not restore untracked files from stash'
+		die "$(gettext "Could not restore untracked files from stash")"
 	fi
 
 	eval "
@@ -518,7 +559,7 @@ pop_stash() {
 		drop_stash "$@"
 	else
 		status=$?
-		say "The stash is kept in case you need it again."
+		say "$(gettext "The stash is kept in case you need it again.")"
 		exit $status
 	fi
 }
